### ISSUE TITLE
Incorrect transitive dependency exclusion

### ISSUE THREAD

**Issue by blindpirate** [blindpirate/gogradle#87]
Suppose there's a `gogradle.lock`:

```
- name: github.com/user/a
  commit: xxx
  transitive: false
- name: github.com/user/b
  host:
      - name: github.com/user/a
         commit: xxx
   vendorPath: vendor/github.com/user/b
   transitive: false
```

Before resolving `github.com/user/b`, `github.com/user/a` will be resolved first, but this course will be affected by `github.com/user/b`'s `transitive:false` and wind up resolved dependency with an empty transitive dependencies.
